# Generated by Django 3.1.7 on 2021-03-29 09:55

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_content_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='enable_viber',
            field=models.BooleanField(default=False, help_text='When enabled, the API will include the viber content'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='viber_body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='viber_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='viber_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
