# Generated by Django 3.1.7 on 2021-05-16 11:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_add_content_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='messenger_body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.TextBlock(help_text='Each paragraph cannot extend over the messenger message limit of 2000 characters'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='viber_body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.TextBlock(help_text='Each paragraph cannot extend over the viber message limit of 7000 characters'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='whatsapp_body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.TextBlock(help_text='Each paragraph cannot extend over the whatsapp message limit of 4096 characters'))], blank=True, null=True),
        ),
    ]
