# Generated by Django 3.2.7 on 2021-09-08 07:27

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_use_text_fields_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='messenger_subtitle',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='viber_subtitle',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='whatsapp_subtitle',
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='messenger_body',
            field=wagtail.fields.StreamField([('messenger_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('message', wagtail.blocks.TextBlock(help_text='each message cannot exceed 2000 characters.', max_lenth=2000))], help_text='Each paragraph cannot extend over the messenger message limit of 2000 characters'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='viber_body',
            field=wagtail.fields.StreamField([('viber_message', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('message', wagtail.blocks.TextBlock(help_text='each message cannot exceed 7000 characters.', max_lenth=7000))], help_text='Each paragraph cannot extend over the viber message limit of 7000 characters'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='whatsapp_body',
            field=wagtail.fields.StreamField([('Whatsapp_Message', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='document', required=False)), ('media', home.models.MediaBlock(icon='media', required=False)), ('message', wagtail.blocks.TextBlock(help_text='each message cannot exceed 4096 characters.', max_lenth=4096))], help_text='Each message will be sent with the paragraph and the image'))], blank=True, null=True),
        ),
    ]
