# Generated by Django 3.2.7 on 2021-09-13 11:34

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_struct_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='whatsapp_body',
            field=wagtail.fields.StreamField([('Whatsapp_Message', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='document', required=False)), ('media', home.models.MediaBlock(icon='media', required=False)), ('message', wagtail.blocks.TextBlock(help_text='each message cannot exceed 4096 characters.', max_lenth=4096))], help_text='Each message will be sent with the text and media'))], blank=True, null=True),
        ),
    ]
