# Generated by Django 3.2.8 on 2021-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contentpagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpageindex',
            name='include_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
