# Generated by Django 3.2.7 on 2021-12-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpagerating',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
