# Generated by Django 3.2.7 on 2022-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211217_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='is_whatsapp_template',
            field=models.BooleanField(default=False),
        ),
    ]
