# Generated by Django 3.2.11 on 2022-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contentpage_is_whatsapp_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='is_whatsapp_template',
            field=models.BooleanField(default=False, verbose_name='Is Template'),
        ),
    ]
