# Generated by Django 3.2.11 on 2022-06-15 11:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220602_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='messenger_quick_replies',
            field=wagtail.core.fields.StreamField([('quick_reply', wagtail.core.blocks.CharBlock(label='Quick reply'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='whatsapp_quick_replies',
            field=wagtail.core.fields.StreamField([('quick_reply', wagtail.core.blocks.CharBlock(label='Quick reply'))], blank=True, null=True),
        ),
    ]
