# Generated by Django 4.0.6 on 2022-07-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('home', '0016_auto_20220615_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='platform',
            field=models.TextField(blank=True, default='web', null=True, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='contentpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
