# Generated by Django 4.0.6 on 2022-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contentquickreply_contenttrigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='platform',
            field=models.CharField(blank=True, choices=[('WHATSAPP', 'whatsapp'), ('VIBER', 'viber'), ('MESSENGER', 'messenger'), ('WEB', 'web')], default='web', max_length=20, null=True),
        ),
    ]
