# Generated by Django 4.1.1 on 2022-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_pageview_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentquickreply",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="contenttrigger",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
