# Generated by Django 4.0.7 on 2022-09-13 07:52

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('home', '0020_pageview_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.ContentPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
