# Generated by Django 4.1.1 on 2022-09-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_contentpage_tags"),
        ("home", "0021_alter_contentquickreply_slug_and_more"),
    ]

    operations = []
