# Generated by Django 4.1.3 on 2022-12-02 13:51

from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_contentpage_whatsapp_body_sitesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="content_variations_options",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="profile_field_options",
            field=wagtail.fields.StreamField(
                [
                    (
                        "gender",
                        wagtail.blocks.MultipleChoiceBlock(
                            choices=[
                                ("male", "Male"),
                                ("female", "Female"),
                                ("non-binary", "Non-Binary"),
                            ]
                        ),
                    ),
                    (
                        "health_literacy_level",
                        wagtail.blocks.MultipleChoiceBlock(
                            choices=[
                                ("low", "Low"),
                                ("medium", "Medium"),
                                ("high", "High"),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="Fields that may be used to restrict content to certain user segments",
                null=True,
                use_json_field=None,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="whatsapp_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Whatsapp_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        icon="document", required=False
                                    ),
                                ),
                                (
                                    "media",
                                    home.models.MediaBlock(
                                        icon="media", required=False
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each message cannot exceed 4096 characters.",
                                        max_lenth=4096,
                                    ),
                                ),
                                (
                                    "variation_messages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "variation_restrictions",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "gender",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_gender_choices
                                                                ),
                                                            ),
                                                            (
                                                                "health_literacy_level",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_health_lit_lvl_choices
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Restrict this variation to users with this profile value. Valid values must be added to the Site Settings",
                                                        max_num=1,
                                                        min_num=1,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "message",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="each message cannot exceed 4096 characters.",
                                                        max_lenth=4096,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "next_prompt",
                                    wagtail.blocks.CharBlock(
                                        help_text="prompt text for next message",
                                        max_length=20,
                                        required=False,
                                    ),
                                ),
                            ],
                            help_text="Each message will be sent with the text and media",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
