# Generated by Django 4.1.3 on 2022-12-08 13:41

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedContentSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_fields",
                    wagtail.fields.StreamField(
                        [
                            (
                                "gender",
                                wagtail.blocks.ChoiceBlock(
                                    choices=home.models.get_gender_choices
                                ),
                            ),
                            (
                                "age",
                                wagtail.blocks.ChoiceBlock(
                                    choices=home.models.get_age_choices
                                ),
                            ),
                            (
                                "relationship",
                                wagtail.blocks.ChoiceBlock(
                                    choices=home.models.get_relationship_choices
                                ),
                            ),
                        ],
                        default=[],
                        help_text="Restrict this ordered set to users with these profile values. Valid values must be added to the Site Settings",
                        use_json_field=True,
                    ),
                ),
                (
                    "pages",
                    wagtail.fields.StreamField(
                        [("pages", wagtail.blocks.PageChooserBlock())],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
        ),
    ]
