# Generated by Django 4.1.3 on 2022-12-05 14:49

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="profile_field_options",
            field=wagtail.fields.StreamField(
                [
                    (
                        "gender",
                        wagtail.blocks.MultipleChoiceBlock(
                            choices=[
                                ("male", "Male"),
                                ("female", "Female"),
                                ("non-binary", "Non-Binary"),
                            ]
                        ),
                    ),
                    (
                        "health_literacy_level",
                        wagtail.blocks.MultipleChoiceBlock(
                            choices=[
                                ("low", "Low"),
                                ("medium", "Medium"),
                                ("high", "High"),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="Fields that may be used to restrict content to certain user segments",
                null=True,
                use_json_field=True,
            ),
        ),
    ]
