# Generated by Django 4.1.3 on 2022-12-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_orderedcontentset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderedcontentset",
            options={
                "verbose_name": "Ordered Content Set",
                "verbose_name_plural": "Ordered Content Sets",
            },
        ),
    ]
