# Generated by Django 4.1.3 on 2022-12-17 22:04

import wagtail.blocks
import wagtail.fields
from django.db import migrations

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_alter_orderedcontentset_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedcontentset",
            name="profile_fields",
            field=wagtail.fields.StreamField(
                [
                    (
                        "gender",
                        wagtail.blocks.ChoiceBlock(
                            choices=home.models.get_gender_choices
                        ),
                    ),
                    (
                        "age",
                        wagtail.blocks.ChoiceBlock(choices=home.models.get_age_choices),
                    ),
                    (
                        "relationship",
                        wagtail.blocks.ChoiceBlock(
                            choices=home.models.get_relationship_choices
                        ),
                    ),
                ],
                blank=True,
                default=[],
                help_text="Restrict this ordered set to users with these profile values. Valid values must be added to the Site Settings",
                use_json_field=True,
            ),
        ),
    ]
