# Generated by Django 4.1.7 on 2023-02-23 14:10

from django.db import migrations
from django.db.models import Count


def rename_duplicate_slugs(Page):
    duplicate_slugs = (
        Page.objects.values("slug")
        .annotate(count=Count("slug"))
        .order_by("-count")
        .filter(count__gt=1)
        .values_list("slug", flat=True)
    )
    for slug in duplicate_slugs:
        pages = Page.objects.filter(slug=slug)
        for i, page in enumerate(pages, start=1):
            page.slug = f"{page.slug}-{i}"
            page.save(update_fields=["slug"])


def run_migration(apps, schema_editor):
    Page = apps.get_model("wagtailcore", "Page")
    rename_duplicate_slugs(Page)


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_alter_orderedcontentset_profile_fields"),
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.RunPython(
            code=run_migration, reverse_code=migrations.RunPython.noop
        )
    ]
