# Generated by Django 4.1.7 on 2023-03-08 10:57

from django.db import migrations, models


def add_previous_template_names(apps, schema_editor):
    """
    The previous way of calculating template names was to use the title and the revision
    number. This adds that as the value for the new whatsapp_template_name field
    """
    ContentPage = apps.get_model("home", "ContentPage")
    for page in ContentPage.objects.filter(is_whatsapp_template=True, whatsapp_template_name=""):
        template_name = f"{page.whatsapp_title}_{page.get_latest_revision().id}"
        page.template_name = template_name.replace(" ", "_")
        page.save(update_fields=["template_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_deduplicate_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="whatsapp_template_name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.RunPython(add_previous_template_names, migrations.RunPython.noop)
    ]
