# Generated by Django 4.1.7 on 2023-03-08 10:57

from django.db import migrations, models


def add_previous_template_names(apps, schema_editor):
    """
    The previous way of calculating template names was to use the title and the revision
    number. This adds that as the value for the new whatsapp_template_name field
    """
    ContentPage = apps.get_model("home", "ContentPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    for page in ContentPage.objects.filter(is_whatsapp_template=True):
        template_prefix = page.whatsapp_title.replace(" ", "_")
        page.whatsapp_template_name = f"{template_prefix}_{page.latest_revision.id}"
        page.save(update_fields=["whatsapp_template_name"])

        revisions = Revision.objects.filter(
            content_type=page.content_type,
            object_id=page.pk,
        )
        for revision in revisions:
            if not revision.content.get("whatsapp_title"):
                continue
            template_prefix = revision.content["whatsapp_title"].replace(" ", "_")
            revision.content["whatsapp_template_name"] = f"{template_prefix}_{revision.pk}"
            revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_deduplicate_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="whatsapp_template_name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.RunPython(add_previous_template_names, migrations.RunPython.noop)
    ]
