# Generated by Django 4.1.5 on 2023-02-27 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_deduplicate_slugs"),
    ]

    operations = [migrations.RunSQL(
        "CREATE UNIQUE INDEX page_unique_slug ON wagtailcore_page(slug)",
        "DROP INDEX page_unique_slug"
    )]
