# Generated by Django 4.1.9 on 2023-06-21 09:23

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("home", "0031_alter_contentpagerating_id_alter_contentpagetag_id_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                 migrations.AlterField(
                    model_name="pageview",
                    name="timestamp",
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="pageview",
                    index=models.Index(fields=["timestamp"], name="timestamp_idx"),
                ),
            ],
        ),
    ]

