# Generated by Django 4.1.7 on 2023-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_alter_contentpagerating_id_alter_contentpagetag_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["timestamp"], name="home_pagevi_timesta_22638e_idx"
            ),
        ),
    ]
