# Generated by Django 4.1.9 on 2023-06-21 09:23

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models

def forwards(apps, schema_editor):
    if not schema_editor.connection.vendor == 'postgres':
        AddIndex = AddIndexConcurrently
    else:
        AddIndex = migrations.AddIndex
    AddIndex(
        model_name="pageview",
        index=models.Index(fields=["timestamp"], name="timestamp_idx"),
    )

def backwards(apps, schema_editor):
    if not schema_editor.connection.vendor == 'postgres':
        RemoveIndex = RemoveIndexConcurrently
    else:
        RemoveIndex = migrations.RemoveIndex
    RemoveIndex(model_name="pageview", name="timestamp_idx")

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("home", "0031_alter_contentpagerating_id_alter_contentpagetag_id_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                 migrations.AlterField(
                    model_name="pageview",
                    name="timestamp",
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
            ],
            database_operations=[
                migrations.RunPython(forwards, backwards)
            ],
        ),
    ]

