# Generated by Django 4.1.10 on 2023-07-06 09:55

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_alter_orderedcontentset_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedcontentset",
            name="name",
            field=models.CharField(
                help_text="The name of the ordered content set.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="orderedcontentset",
            name="pages",
            field=wagtail.fields.StreamField(
                [
                    (
                        "pages",
                        wagtail.blocks.StructBlock(
                            [
                                ("contentpage", wagtail.blocks.PageChooserBlock()),
                                (
                                    "time",
                                    wagtail.blocks.IntegerBlock(
                                        min_value=0, required=False
                                    ),
                                ),
                                (
                                    "unit",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("minutes", "Minutes"),
                                            ("hours", "Hours"),
                                            ("days", "Days"),
                                            ("months", "Months"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "before_or_after",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("after", "After"),
                                            ("before", "Before"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "contact_field",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
