# Generated by Django 4.1.10 on 2023-07-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_alter_orderedcontentset_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="login_message",
            field=models.CharField(
                blank=True,
                help_text="The login message shown on the login page",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The branding title shown in the CMS",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="welcome_message",
            field=models.CharField(
                blank=True,
                help_text="The welcome message shown after logging in",
                max_length=100,
                null=True,
            ),
        ),
    ]
