# Generated by Django 4.1.10 on 2023-07-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0034_sitesettings_favicon_sitesettings_login_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
