# Generated by Django 4.1.10 on 2023-09-21 12:29

from uuid import uuid4

import django.core.validators
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation

import home.models


def copy_next_prompt_to_next_button_for_message(message):
        next_prompt = message["value"].get("next_prompt")
        if not next_prompt:
            return
        # Buttons have just been added, so there are no buttons defined yet
        message["value"]["buttons"] = [{"id": str(uuid4()), "type": "next_message", "value": {"title": next_prompt}}]

class CopyNextPromptToNextButtonOperation(BaseBlockOperation):
    def apply(self, block_value):
        for message in block_value:
            copy_next_prompt_to_next_button_for_message(message)
        return block_value

    @property
    def operation_name_fragment(self):
        return "copy_next_prompt_to_next_button"


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_alter_contentpage_messenger_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="whatsapp_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Whatsapp_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        icon="document", required=False
                                    ),
                                ),
                                (
                                    "media",
                                    home.models.MediaBlock(
                                        icon="media", required=False
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each text message cannot exceed 4096 characters, messages with media cannot exceed 1024 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                4096
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "variation_messages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "variation_restrictions",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "gender",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_gender_choices
                                                                ),
                                                            ),
                                                            (
                                                                "age",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_age_choices
                                                                ),
                                                            ),
                                                            (
                                                                "relationship",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_relationship_choices
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Restrict this variation to users with this profile value. Valid values must be added to the Site Settings",
                                                        max_num=1,
                                                        min_num=1,
                                                        required=False,
                                                        use_json_field=True,
                                                    ),
                                                ),
                                                (
                                                    "message",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="each message cannot exceed 4096 characters.",
                                                        validators=(
                                                            django.core.validators.MaxLengthValidator(
                                                                4096
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                    ),
                                ),
                                (
                                    "next_prompt",
                                    wagtail.blocks.CharBlock(
                                        help_text="prompt text for next message",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="page the button should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        max_num=3,
                                        required=False,
                                    ),
                                ),
                            ],
                            help_text="Each message will be sent with the text and media",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        MigrateStreamData(
            app_name="home",
            model_name="ContentPage",
            field_name="whatsapp_body",
            operations_and_block_paths=[(CopyNextPromptToNextButtonOperation(), "")]
        ),
    ]
