# Generated by Django 4.1.10 on 2023-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="whatsapp_template_category",
            field=models.CharField(
                choices=[
                    ("AUTHENTICATION", "Authentication"),
                    ("MARKETING", "Marketing"),
                    ("UTILITY", "Utility"),
                ],
                default="UTILITY",
                max_length=14,
            ),
        ),
    ]
