# Generated by Django 4.1.10 on 2023-10-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_contentpage_whatsapp_template_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="whatsapp_template_category",
            field=models.CharField(
                choices=[("MARKETING", "Marketing"), ("UTILITY", "Utility")],
                default="UTILITY",
                max_length=14,
            ),
        ),
    ]
