# Generated by Django 4.1.11 on 2024-01-08 10:24

import django.core.validators
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_alter_contentpage_whatsapp_template_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="enable_sms",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the API will include the sms content",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="sms_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "SMS_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each message cannot exceed 160 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                160
                                            ),
                                        ),
                                    ),
                                )
                            ],
                            help_text="Each message will be sent with the text",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="sms_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
