# Generated by Django 4.1.13 on 2024-01-08 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_alter_contentpage_whatsapp_template_category"),
        ("home", "0041_contentpage_whatsapp_template_lower_case_name"),
    ]

    operations = []
