# Generated by Django 4.1.11 on 2024-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_contentpage_enable_sms_contentpage_sms_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="sms_title",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pageview",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WHATSAPP", "whatsapp"),
                    ("SMS", "sms"),
                    ("VIBER", "viber"),
                    ("MESSENGER", "messenger"),
                    ("WEB", "web"),
                ],
                default="web",
                max_length=20,
                null=True,
            ),
        ),
    ]
