# Generated by Django 4.1.11 on 2024-01-22 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_contentpage_enable_sms_contentpage_sms_body_and_more"),
        ("home", "0041_contentpage_whatsapp_template_lower_case_name"),
    ]

    operations = []
