# Generated by Django 4.1.11 on 2024-01-22 09:12

import django.core.validators
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_merge_20240122_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="enable_ussd",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the API will include the USSD content",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="ussd_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "USSD_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each message cannot exceed 160 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                160
                                            ),
                                        ),
                                    ),
                                )
                            ],
                            help_text="Each message will be sent with the text",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="ussd_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="enable_sms",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the API will include the SMS content",
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="sms_title",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pageview",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WHATSAPP", "whatsapp"),
                    ("SMS", "sms"),
                    ("USSD", "ussd"),
                    ("VIBER", "viber"),
                    ("MESSENGER", "messenger"),
                    ("WEB", "web"),
                ],
                default="web",
                max_length=20,
                null=True,
            ),
        ),
    ]
