# Generated by Django 4.1.11 on 2024-01-18 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_contentpage_whatsapp_template_lower_case_name"),
        ("home", "0043_contentpage_enable_ussd_contentpage_ussd_body_and_more"),
    ]

    operations = []