# Generated by Django 4.2.9 on 2024-01-23 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_alter_contentpage_whatsapp_body"),
        ("home", "0044_merge_20240118_1014"),
    ]

    operations = []
