# Generated by Django 4.2.11 on 2024-03-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0049_assessment_assessmenttag_assessment_tags"),
        ("home", "0049_orderedcontentset_expire_at_and_more"),
    ]

    operations = []
