# Generated by Django 4.2.11 on 2024-03-22 11:33

import django.core.validators
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_orderedcontentset_locked_orderedcontentset_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="sms_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "SMS_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each message cannot exceed 459 characters (3 messages).",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                459
                                            ),
                                        ),
                                    ),
                                )
                            ],
                            help_text="Each message will be sent with the text",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
