# Generated by Django 4.2.11 on 2024-03-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0050_templatecontentquickreply_templatequickreplycontent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="related_pages",
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image",
                to="wagtailimages.image",
            ),
        ),
    ]
