# Generated by Django 4.1.11 on 2024-03-13 09:41

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_whatsapptemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateContentQuickReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "quick reply2",
                "verbose_name_plural": "quick replie2",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsapptemplate",
            options={
                "verbose_name": "WhatsApp Template",
                "verbose_name_plural": "WhatsApp Templates",
            },
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="related_pages",
            field=wagtail.fields.StreamField(
                [("related_page", wagtail.blocks.PageChooserBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="TemplateQuickReplyContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_quick_reply_items",
                        to="home.whatsapptemplate",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_quick_reply_content",
                        to="home.templatecontentquickreply",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="quick_replies",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="home.TemplateQuickReplyContent",
                to="home.TemplateContentQuickReply",
                verbose_name="Tags",
            ),
        ),
    ]
