# Generated by Django 4.1.11 on 2024-03-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0085_alter_page_slug"),
        ("home", "0051_whatsapptemplate_expire_at_whatsapptemplate_expired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="locale",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.locale",
            ),
        ),
    ]
