# Generated by Django 4.2.11 on 2024-03-18 13:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_remove_whatsapptemplate_related_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="related_pages",
            field=wagtail.fields.StreamField(
                [("related_page", wagtail.blocks.PageChooserBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
