# Generated by Django 4.2.11 on 2024-03-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_alter_contentpage_sms_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="embedding",
        ),
    ]
