# Generated by Django 4.2.11 on 2024-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0052_whatsapptemplate_related_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateExampleValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=512)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
            ],
        ),
    ]
