# Generated by Django 4.1.11 on 2024-03-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0052_whatsapptemplate_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="locale",
        ),
    ]
