# Generated by Django 4.2.11 on 2024-04-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0052_templatecontentquickreply_templatequickreplycontent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="submission_name",
            field=models.TextField(
                blank=True,
                help_text="The name of the template that was submitted",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="submission_result",
            field=models.TextField(
                blank=True,
                help_text="The result of submitting the template",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="submission_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_SUBMITTED_YET", "Not Submitted Yet"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_SUBMITTED_YET",
                max_length=30,
            ),
        ),
    ]
