# Generated by Django 4.2.11 on 2024-04-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0049_assessment_assessmenttag_assessment_tags"),
        ("home", "0052_templatecontentquickreply_templatequickreplycontent_and_more"),
    ]

    operations = []
