# Generated by Django 4.2.11 on 2024-04-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_merge_20240304_1424"),
        ("home", "0052_templatecontentquickreply_templatequickreplycontent_and_more"),
    ]

    operations = []
