# Generated by Django 4.2.11 on 2024-03-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_templateexamplevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="example_values",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="example_values",
                to="home.templateexamplevalue",
            ),
        ),
    ]
