# Generated by Django 4.2.11 on 2024-04-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_merge_20240404_1505"),
        ("home", "0053_whatsapptemplate_submission_name_and_more"),
    ]

    operations = []
