# Generated by Django 4.2.11 on 2024-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0054_merge_20240430_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="submission_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The name of the template that was submitted",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="submission_result",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The result of submitting the template",
                max_length=4096,
            ),
        ),
    ]
