# Generated by Django 4.2.11 on 2024-03-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0054_whatsapptemplate_example_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateexamplevalue",
            name="description",
        ),
    ]
