# Generated by Django 4.2.11 on 2024-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0055_remove_templateexamplevalue_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateexamplevalue",
            name="name",
            field=models.CharField(blank=True, default="Test", max_length=512),
        ),
    ]
