# Generated by Django 4.2.11 on 2024-03-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0058_remove_whatsapptemplate_example_values_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="example_values",
        ),
    ]
