# Generated by Django 4.2.11 on 2024-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0058_alter_assessment_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="version",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
