# Generated by Django 4.2.11 on 2024-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0060_alter_assessment_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="A version number to distinguish between question sets",
                max_length=255,
                null=True,
            ),
        ),
    ]
