# Generated by Django 4.2.11 on 2024-03-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0061_templateexamplevalue_whatsapptemplate_example_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="example_values",
        ),
        migrations.DeleteModel(
            name="TemplateExampleValue",
        ),
    ]
