# Generated by Django 4.2.11 on 2024-03-19 12:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0062_remove_whatsapptemplate_example_values_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="example_values_stream",
            field=wagtail.fields.StreamField(
                [
                    (
                        "example_values",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.CharBlock(label="Example Value"),
                            default=[],
                            help_text="Please add example values for all variables used in a WhatsApp template",
                            label="Variable Example Values",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
