# Generated by Django 4.2.11 on 2024-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0062_alter_assessment_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="version",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
