# Generated by Django 4.2.11 on 2024-03-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0063_whatsapptemplate_example_values_stream"),
    ]

    operations = [
        migrations.RenameField(
            model_name="whatsapptemplate",
            old_name="example_values_stream",
            new_name="example_values",
        ),
    ]
