# Generated by Django 4.2.11 on 2024-06-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0063_alter_assessment_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessment",
            old_name="version",
            new_name="form_version",
        ),
    ]
