# Generated by Django 4.2.11 on 2024-03-20 09:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0064_rename_example_values_stream_whatsapptemplate_example_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="example_values",
            field=wagtail.fields.StreamField(
                [("example_values", wagtail.blocks.CharBlock(label="Example Value"))],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
