# Generated by Django 4.2.11 on 2024-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0065_alter_whatsapptemplate_example_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="category",
            field=models.CharField(
                choices=[("UTILITY", "Utility"), ("MARKETING", "Marketing")],
                default="MARKETING",
                max_length=14,
            ),
        ),
    ]
