# Generated by Django 4.2.11 on 2024-06-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0065_rename_form_version_assessment_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A version number for the question set",
                max_length=200,
            ),
        ),
    ]
