# Generated by Django 4.2.11 on 2024-06-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0072_alter_assessment_high_inflection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="high_inflection",
            field=models.FloatField(
                blank=True,
                help_text="Any score equal to or above this amount is considered high",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="high_result_page",
            field=models.ForeignKey(
                blank=True,
                help_text="The page to show the user if they score high",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_high",
                to="home.contentpage",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="low_result_page",
            field=models.ForeignKey(
                blank=True,
                help_text="The page to show the user if they score low",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_low",
                to="home.contentpage",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="medium_inflection",
            field=models.FloatField(
                blank=True,
                help_text="Any score equal to or above this amount, but lower than the high inflection, is considered medium. Any score below this amount is considered low",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="medium_result_page",
            field=models.ForeignKey(
                blank=True,
                help_text="The page to show the user if they score medium",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_medium",
                to="home.contentpage",
            ),
        ),
    ]
