# Generated by Django 4.2.11 on 2024-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0077_alter_assessment_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="high_inflection",
            field=models.FloatField(
                blank=True,
                help_text="Any score equal to or above this amount is considered high. Note that this is a percentage-based number.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="medium_inflection",
            field=models.FloatField(
                blank=True,
                help_text="Any score equal to or above this amount, but lower than the high inflection, is considered medium. Any score below this amount is considered low. Note that this is a percentage-based number.",
                null=True,
            ),
        ),
    ]
