# Generated by Django 4.2.11 on 2024-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0078_alter_assessment_high_inflection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="message",
            field=models.TextField(
                help_text="each template message cannot exceed 1024 characters",
                max_length=1024,
            ),
        ),
    ]
