# Generated by Django 4.2.11 on 2024-08-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0080_assessment_skip_high_result_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="embedding",
        ),
    ]
