# Generated by Django 4.2.11 on 2024-11-13 13:56

import django.core.validators
from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation
from wagtail.blocks.migrations.utils import formatted_list_child_generator
import home.models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


def list_string_to_action(block_value):
    # formatted_list_child_generator requires at least one item
    if not block_value:
        return block_value
    new_list = []
    for list_item in formatted_list_child_generator(block_value):
        print(f"list_item {list_item}")
        new_list.append(
            {
                "type": "next_message",
                "id": list_item["id"],
                "value": {"title": list_item["value"]},
            }
        )
    return new_list


class ListStringToActionOperation(BaseBlockOperation):
    def apply(self, block_value):
        list_string_to_action(block_value)

    @property
    def operation_name_fragment(self):
        return "convert_list_string_to_action"


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0082_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        MigrateStreamData(
            app_name="home",
            model_name="ContentPage",
            field_name="whatsapp_body",
            operations_and_block_paths=[
                (ListStringToActionOperation(), "Whatsapp_Message.list_items")
            ],
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="whatsapp_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Whatsapp_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        icon="document", required=False
                                    ),
                                ),
                                (
                                    "media",
                                    home.models.MediaBlock(
                                        icon="media", required=False
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each text message cannot exceed 4096 characters, messages with media cannot exceed 1024 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                4096
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "example_values",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.CharBlock(label="Example Value"),
                                        default=[],
                                        help_text="Please add example values for all variables used in a WhatsApp template",
                                        label="Variable Example Values",
                                    ),
                                ),
                                (
                                    "variation_messages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "variation_restrictions",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "gender",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_gender_choices
                                                                ),
                                                            ),
                                                            (
                                                                "age",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_age_choices
                                                                ),
                                                            ),
                                                            (
                                                                "relationship",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_relationship_choices
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Restrict this variation to users with this profile value. Valid values must be added to the Site Settings",
                                                        max_num=1,
                                                        min_num=1,
                                                        required=False,
                                                        use_json_field=True,
                                                    ),
                                                ),
                                                (
                                                    "message",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="each message cannot exceed 4096 characters.",
                                                        validators=(
                                                            django.core.validators.MaxLengthValidator(
                                                                4096
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                    ),
                                ),
                                (
                                    "next_prompt",
                                    wagtail.blocks.CharBlock(
                                        help_text="prompt text for next message",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Page the button should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        max_num=3,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="List title, up to 24 characters.",
                                        max_length=24,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the list item, up to 24 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        24
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the list item, up to 24 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        24
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Page the list item should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        help_text="Items to appear in the list message",
                                        max_num=10,
                                        required=False,
                                    ),
                                ),
                                (
                                    "footer",
                                    wagtail.blocks.CharBlock(
                                        help_text="Footer cannot exceed 60 characters.",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                60
                                            ),
                                        ),
                                    ),
                                ),
                            ],
                            help_text="Each message will be sent with the text and media",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
