# Generated by Django 4.2.11 on 2024-10-30 14:18

import django.core.validators
from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


def migrate_list_items(ContentPage):
    """
    Migrate the list items in the whatsapp_body field to the new format
    """
    for page in ContentPage.objects.filter(is_whatsapp_template=True):
        if not page.whatsapp_body.raw_data[0]["value"]["list_items"]:
            continue
        list_items = [
            {"type": "next_message", "value": {"title": item["value"]}}
            for item in page.whatsapp_body.raw_data[0]["value"]["list_items"]
        ]
        page.whatsapp_body.raw_data[0]["value"]["list_items"] = list_items
        page.save()


def run_migration(apps, schema_editor):
    ContentPage = apps.get_model("home", "ContentPage")
    migrate_list_items(ContentPage)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0082_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="whatsapp_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Whatsapp_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        icon="document", required=False
                                    ),
                                ),
                                (
                                    "media",
                                    home.models.MediaBlock(
                                        icon="media", required=False
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each text message cannot exceed 4096 characters, messages with media cannot exceed 1024 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                4096
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "example_values",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.CharBlock(label="Example Value"),
                                        default=[],
                                        help_text="Please add example values for all variables used in a WhatsApp template",
                                        label="Variable Example Values",
                                    ),
                                ),
                                (
                                    "variation_messages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "variation_restrictions",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "gender",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_gender_choices
                                                                ),
                                                            ),
                                                            (
                                                                "age",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_age_choices
                                                                ),
                                                            ),
                                                            (
                                                                "relationship",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_relationship_choices
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Restrict this variation to users with this profile value. Valid values must be added to the Site Settings",
                                                        max_num=1,
                                                        min_num=1,
                                                        required=False,
                                                        use_json_field=True,
                                                    ),
                                                ),
                                                (
                                                    "message",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="each message cannot exceed 4096 characters.",
                                                        validators=(
                                                            django.core.validators.MaxLengthValidator(
                                                                4096
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                    ),
                                ),
                                (
                                    "next_prompt",
                                    wagtail.blocks.CharBlock(
                                        help_text="prompt text for next message",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button / list item, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button / list item, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Page the button / list item should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        max_num=3,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_button_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="List button title, up to 24 characters.",
                                        max_length=24,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button / list item, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button / list item, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Page the button / list item should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        default=[],
                                        help_text="List item title, up to 24 characters.",
                                        max_num=10,
                                        required=False,
                                    ),
                                ),
                                (
                                    "footer",
                                    wagtail.blocks.CharBlock(
                                        help_text="Footer cannot exceed 60 characters.",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                60
                                            ),
                                        ),
                                    ),
                                ),
                            ],
                            help_text="Each message will be sent with the text and media",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.RunPython(run_migration, migrations.RunPython.noop),
    ]
