# Generated by Django 4.2.11 on 2024-11-19 09:08


from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation
from django.db import migrations


def list_items_to_empty(block_value):
    if not block_value:
        return []
    return block_value


class ListItemsToEmptyOperation(BaseBlockOperation):
    def apply(self, block_value):
        return list_items_to_empty(block_value)

    @property
    def operation_name_fragment(self):
        return "convert_list_items_to_empty"


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0083_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        MigrateStreamData(
            app_name="home",
            model_name="ContentPage",
            field_name="whatsapp_body",
            operations_and_block_paths=[
                (ListItemsToEmptyOperation(), "Whatsapp_Message.list_items")
            ],
        ),
    ]
