# Generated by Django 4.2.11 on 2024-11-25 12:05

from django.db import migrations, models
from django.db.models import Count
import django.db.models.deletion
import home.models


def rename_duplicate_slugs(OrderedContentSet):
    duplicate_slugs = (
        OrderedContentSet.objects.values("slug")
        .annotate(count=Count("slug"))
        .order_by("-count")
        .filter(count__gt=1)
        .values_list("slug", flat=True)
    )
    for slug in duplicate_slugs:
        ordered_content_sets = OrderedContentSet.objects.filter(slug=slug)
        for ordered_content_set in ordered_content_sets:
            slug_from_name = (
                ordered_content_set.name.lower().replace(" ", "-").replace("_", "-")
            )
            suffix = 0
            candidate_slug = slug_from_name
            while OrderedContentSet.objects.filter(slug=candidate_slug).exists():
                suffix += 1
                candidate_slug = f"{slug_from_name}-{suffix}"

            ordered_content_set.slug = candidate_slug
            ordered_content_set.save(update_fields=["slug"])


def set_locale_from_instance(OrderedContentSet, Site):
    site = Site.objects.get(is_default_site=True)
    default_locale_id = site.root_page.locale_id

    for ocs in OrderedContentSet.objects.all():
        if ocs.pages:
            # Get the first page's data
            first_page_data = ocs.pages[0]
            if isinstance(first_page_data, tuple):
                contentpage = first_page_data[1].get("contentpage")
            else:
                contentpage = first_page_data.value.get("contentpage")

            if contentpage:
                ocs.locale_id = contentpage.locale_id
            else:
                ocs.locale_id = default_locale_id
        else:
            ocs.locale_id = default_locale_id
        ocs.save(update_fields=["locale_id"])


def run_migration(apps, schema_editor):
    OrderedContentSet = apps.get_model("home", "OrderedContentSet")
    Site = apps.get_model("wagtailcore", "Site")
    rename_duplicate_slugs(OrderedContentSet)
    set_locale_from_instance(OrderedContentSet, Site)


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0084_alter_contentpage_whatsapp_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedcontentset",
            name="locale",
            field=models.ForeignKey(
                default=home.models._get_default_locale,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="orderedcontentset",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="A unique identifier for this ordered content set",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            code=run_migration, reverse_code=migrations.RunPython.noop
        ),
    ]
