# Generated by Django 4.2.17 on 2025-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0090_alter_orderedcontentset_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="slug",
            field=models.SlugField(
                help_text="A unique identifier for this CMS Form", max_length=255
            ),
        ),
    ]
