# Generated by Django 4.2.20 on 2025-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0091_alter_assessment_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="whatsapptemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "locale"), name="unique_name_locale"
            ),
        ),
    ]
