# Generated by Django 4.2.20 on 2025-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0093_alter_contentpage_whatsapp_body_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="whatsapptemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "locale"), name="unique_name_locale"
            ),
        ),
    ]
