# Generated by Django 4.2.17 on 2025-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0093_alter_contentpage_whatsapp_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED_YET", "Not Submitted Yet"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_SUBMITTED_YET",
                max_length=30,
            ),
        ),
    ]
