# Generated by Django 4.2.17 on 2025-04-10 12:18

from django.db import migrations
from typing import Any


def set_blank_submission_status_to_not_submitted_yet(WhatsAppTemplate: Any) -> None:
    wa_templates = WhatsAppTemplate.objects.all()
    for wa_template in wa_templates:
        if not wa_template.submission_status:
            wa_template.submission_status = "NOT_SUBMITTED_YET"
            wa_template.save(update_fields=["submission_status"])


def run_migration(apps: Any, schema_editor: Any) -> None:
    WhatsAppTemplate = apps.get_model("home", "WhatsAppTemplate")
    set_blank_submission_status_to_not_submitted_yet(WhatsAppTemplate)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0094_alter_whatsapptemplate_submission_status"),
    ]

    operations = [
        migrations.RunPython(
            code=run_migration, reverse_code=migrations.RunPython.noop
        ),
    ]
