# Generated by Django 4.2.20 on 2025-04-29 11:07

import django.core.validators
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0096_migrate_empty_submission_status_to_not_submitted_yet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="buttons",
            field=wagtail.fields.StreamField(
                [
                    (
                        "next_message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Text for the button, up to 20 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "go_to_page",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Text for the button, up to 20 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="Page the button should go to"
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "go_to_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Text for the button, up to 20 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "form",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        "home.Assessment",
                                        help_text="Form the button should start",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
