# Generated by Django 4.2.20 on 2025-04-30 14:44

import django.core.validators
from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0098_migrate_content_page_templates_to_standalone_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="is_whatsapp_template",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="whatsapp_template_category",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="whatsapp_template_name",
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="whatsapp_body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Whatsapp_Message",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        icon="document", required=False
                                    ),
                                ),
                                (
                                    "media",
                                    home.models.MediaBlock(
                                        icon="media", required=False
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.blocks.TextBlock(
                                        help_text="each text message cannot exceed 4096 characters, messages with media cannot exceed 1024 characters.",
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                4096
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "variation_messages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "variation_restrictions",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "gender",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_gender_choices
                                                                ),
                                                            ),
                                                            (
                                                                "age",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_age_choices
                                                                ),
                                                            ),
                                                            (
                                                                "relationship",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=home.models.get_relationship_choices
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Restrict this variation to users with this profile value. Valid values must be added to the Site Settings",
                                                        max_num=1,
                                                        min_num=1,
                                                        required=False,
                                                        use_json_field=True,
                                                    ),
                                                ),
                                                (
                                                    "message",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="each message cannot exceed 4096 characters.",
                                                        validators=(
                                                            django.core.validators.MaxLengthValidator(
                                                                4096
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                    ),
                                ),
                                (
                                    "next_prompt",
                                    wagtail.blocks.CharBlock(
                                        help_text="prompt text for next message",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                20
                                            ),
                                        ),
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Page the button should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_form",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the button, up to 20 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        20
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "form",
                                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                                "home.Assessment",
                                                                help_text="Form the button should start",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        max_num=3,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="List title, up to 24 characters.",
                                        max_length=24,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_items",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "next_message",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the list item, up to 24 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        24
                                                                    ),
                                                                ),
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_page",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the list item, up to 24 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        24
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Page the list item should go to"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "go_to_form",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text for the list item, up to 24 characters.",
                                                                validators=(
                                                                    django.core.validators.MaxLengthValidator(
                                                                        24
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        (
                                                            "form",
                                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                                "home.Assessment",
                                                                help_text="Form the list item should start",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        help_text="Items to appear in the list message",
                                        max_num=10,
                                        required=False,
                                    ),
                                ),
                                (
                                    "footer",
                                    wagtail.blocks.CharBlock(
                                        help_text="Footer cannot exceed 60 characters.",
                                        required=False,
                                        validators=(
                                            django.core.validators.MaxLengthValidator(
                                                60
                                            ),
                                        ),
                                    ),
                                ),
                            ],
                            help_text="Each message will be sent with the text and media",
                        ),
                    ),
                    (
                        "Whatsapp_Template",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "home.WhatsAppTemplate", help_text="WhatsAppTemplate to use"
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
