# Generated by Django 4.2.20 on 2025-05-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0100_remove_contentpage_is_whatsapp_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.locale"
            ),
        ),
    ]
