# Generated by Django 4.2.20 on 2025-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0101_alter_whatsapptemplate_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="A unique identifier for this WhatsApp Template",
                max_length=255,
            ),
        ),
    ]
