# Generated by Django 4.2.20 on 2025-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0101_alter_whatsapptemplate_locale"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="whatsapptemplate",
            name="unique_name_locale",
        ),
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="name",
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="A unique identifier for this WhatsApp Template",
                max_length=255,
            ),
        ),
       
        migrations.AddConstraint(
            model_name="whatsapptemplate",
            constraint=models.UniqueConstraint(
                fields=("slug", "locale"), name="unique_slug_locale"
            ),
        ),
    ]
