# Generated by Django 4.2.20 on 2025-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0103_data_migration_name_to_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="whatsapptemplate",
            name="unique_name_locale",
        ),
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="name",
        ),
        migrations.AddConstraint(
            model_name="whatsapptemplate",
            constraint=models.UniqueConstraint(
                fields=("slug", "locale"), name="unique_slug_locale"
            ),
        ),
    ]
