# Generated by Django 4.2.20 on 2025-07-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0105_templatetag_whatsapptemplate_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="depth",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="home.whatsapptemplate",
            ),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="path",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
