# Generated by Django 4.2.20 on 2025-07-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0106_whatsapptemplate_depth_whatsapptemplate_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="whatsapptemplate",
            name="path",
        ),
        migrations.CreateModel(
            name="WhatsAppTemplateFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the folder", max_length=255
                    ),
                ),
                ("depth", models.PositiveIntegerField(default=0, editable=False)),
                ("path", models.CharField(blank=True, editable=False, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="home.whatsapptemplatefolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Template Folder",
                "verbose_name_plural": "WhatsApp Template Folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="home.whatsapptemplatefolder",
            ),
        ),
    ]
