  graph TD;
      Pages --> Homepage
      Homepage -->ContentPageIndex;
      ContentPageIndex -->ContentPage;
      ContentPage -->Web;
      ContentPage -->WhatsApp;
      ContentPage -->SMS;
      ContentPage -->USSD;
      ContentPage -->Viber;
      ContentPage --> Messenger
     

