name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: ['14']
        python-version: [3.10.6]
        redis-version: ['7.2']
    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        env:
          POSTGRES_DB: contentrepo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379
    env:
      CONTENTREPO_DATABASE: postgres://postgres:postgres@localhost:5432/contentrepo
      CACHE_URL: redis://localhost:6379/0

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: "0.11.18"
        enable-cache: true
    - name: Install dependencies
      id: install-deps
      run: |
        uv sync --locked --dev
    - name: Check formatting
      # Lints/tests should always run, even if other lints/tests have failed.
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        uv run ruff format --check .
    - name: Lint
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        uv run ruff check .
    - name: Check types
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        uv run ty check
    - name: Run tests
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        uv run pytest -vv
    - name: Coverage comment
      id: coverage_comment
      uses: py-cov-action/python-coverage-comment-action@63f52f4fbbffada6e8dee8ec432de7e01df9ba79  # v3.41
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
